[package]
name = "rust-cv"
version = "0.1.0"
authors = ["Oscar Forner Martinez <oscar.forner.martinez@gmail.com>"]
description = ""
keywords = ["cv"]
license = "BSD-2-Clause"

[dependencies]
tui = "0.1.3"
log = "0.3.8"
log4rs = "0.5.2"
termion = "1.4.0"
rand = "0.3.15"
